# Generated by Django 3.0.5 on 2020-04-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimg',
            options={'verbose_name': 'picture', 'verbose_name_plural': 'pictures '},
        ),
        migrations.AlterField(
            model_name='productimg',
            name='image',
            field=models.ImageField(upload_to='products_images/'),
        ),
    ]
