# Generated by Django 3.0.5 on 2020-04-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200415_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='status',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='amount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
